---
development:
  cloud_name: ddkb37s37
  api_key: '973579412448767'
  api_secret: 5dJY0kZ9SZs-ydXfeXVNJhTGq1U
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: ddkb37s37
  api_key: '973579412448767'
  api_secret: 5dJY0kZ9SZs-ydXfeXVNJhTGq1U
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: ddkb37s37
  api_key: '973579412448767'
  api_secret: 5dJY0kZ9SZs-ydXfeXVNJhTGq1U
  enhance_image_tag: true
  static_image_support: false
